export const GenderOptions = ['male','female','other','prefer not to say']

export const PatientFormDefaultValues = {
  name: "",
  email: "",
  phone: "",
  birthDate: new Date(Date.now()),
  gender: "male" as Gender,
  address: "",
  occupation: "",
  emergencyContactName: "",
  emergencyContactNumber: "",
  primaryDoctor: "",
  insuranceProvider: "",
  insurancePolicyNumber: "",
  allergies: "",
  currentMedication: "",
  familyMedicalHistory: "",
  pastMedicalHistory: "",
  identificationType: "Birth Certificate",
  identificationNumber: "",
  identificationDocument: [],
  treatmentConsent: false,
  disclosureConsent: false,
  privacyConsent: false,
};

export const IdentificationTypes = [
  "Birth Certificate",
  "Driver's License",
  "Medical Insurance Card/Policy",
  // "Military ID Card",
  "Aadhar KYC",
  "Passport",
  // "Resident Alien Card (Green Card)",
  // "Social Security Card",
  // "State ID Card",
  "Student ID Card",
  "Voter ID Card",
];

export const Doctors = [
  {
    image: "/assets/images/dr-green.png",
    name: "John Green",
    specialization: "General Medicine",
    experience: "12 yrs",
    qualification: "MBBS, MD (General Medicine)",
    hospital: "CareSync Medical Center",
    address: "12, MG Road, Connaught Place, New Delhi - 110001",
    phone: "+91 98100 12345",
    email: "dr.johngreen@caresync.in",
    availableDays: ["Monday", "Wednesday", "Friday"],
    consultationHours: "9:00 AM - 5:00 PM",
    consultationFee: 800,
    rating: 4.8,
    totalPatients: 1240,
    about: "Dr. John Green is a seasoned general physician with over 12 yrs of experience in diagnosing and treating a wide range of medical conditions. He is known for his patient-first approach and clear communication style.",
    languages: ["English", "Hindi"],
    gender: "male",
    appointmentSpan: '30 mins',
  },
  {
    image: "/assets/images/dr-cameron.png",
    name: "Leila Cameron",
    specialization: "Cardiology",
    experience: "9 yrs",
    qualification: "MBBS, DM (Cardiology)",
    hospital: "CareSync Heart Institute",
    address: "45, Bandra Kurla Complex, Mumbai - 400051",
    phone: "+91 98200 54321",
    email: "dr.leilacameron@caresync.in",
    availableDays: ["Tuesday", "Thursday", "Saturday"],
    consultationHours: "10:00 AM - 4:00 PM",
    consultationFee: 1200,
    rating: 4.9,
    totalPatients: 980,
    about: "Dr. Leila Cameron is a highly regarded cardiologist specializing in interventional cardiology and heart failure management. She has published numerous research papers and is a fellow of the Indian College of Cardiology.",
    languages: ["English", "Hindi", "Urdu"],
    gender: "female",appointmentSpan: '30 mins',
  },
  {
    image: "/assets/images/dr-livingston.png",
    name: "David Livingston",
    specialization: "Neurology",
    experience: "15 yrs",
    qualification: "MBBS, DM (Neurology)",
    hospital: "CareSync Neuro Institute",
    address: "55, Park Street, Kolkata - 700016",
    phone: "+91 93700 77889",
    email: "dr.davidlivingston@caresync.in",
    availableDays: ["Monday", "Tuesday", "Friday"],
    consultationHours: "9:00 AM - 4:00 PM",
    consultationFee: 1400,
    rating: 4.9,
    totalPatients: 1380,
    about: "Dr. David Livingston is a leading neurologist with expertise in stroke management, epilepsy, and movement disorders. He is known for his meticulous diagnostic skills and dedication to neurological research.",
    languages: ["English", "Hindi", "Bengali"],
    gender: "male",appointmentSpan: 'Not Given',
  },
  {
    image: "/assets/images/dr-peter.png",
    name: "Evan Peter",
    specialization: "Dentistry",
    experience: "7 yrs",
    qualification: "BDS, MDS (Orthodontics)",
    hospital: "CareSync Dental Clinic",
    address: "8, Koregaon Park, Pune - 411001",
    phone: "+91 97300 67890",
    email: "dr.evanpeter@caresync.in",
    availableDays: ["Monday", "Tuesday", "Thursday", "Friday"],
    consultationHours: "9:30 AM - 6:00 PM",
    consultationFee: 600,
    rating: 4.7,
    totalPatients: 760,
    about: "Dr. Evan Peter is a skilled dentist specializing in orthodontics and cosmetic dentistry. He is passionate about creating confident smiles and uses the latest technology for pain-free treatments.",
    languages: ["English", "Marathi", "Hindi"],
    gender: "male",appointmentSpan: '1 hour',
  },
  {
    image: "/assets/images/dr-powell.png",
    name: "Jane Powell",
    specialization: "Pediatrics",
    experience: "11 yrs",
    qualification: "MBBS, MD (Pediatrics)",
    hospital: "CareSync Children's Hospital",
    address: "22, Jubilee Hills, Hyderabad - 500033",
    phone: "+91 96400 11223",
    email: "dr.janepoweil@caresync.in",
    availableDays: ["Monday", "Wednesday", "Thursday", "Saturday"],
    consultationHours: "8:00 AM - 3:00 PM",
    consultationFee: 900,
    rating: 4.9,
    totalPatients: 1560,
    about: "Dr. Jane Powell is a compassionate pediatrician with over 11 yrs of experience caring for children from newborns to adolescents. She is especially known for her gentle approach with young patients.",
    languages: ["English", "Hindi", "Telugu"],
    gender: "female",appointmentSpan: '30 mins',
  },
  {
    image: "/assets/images/dr-remirez.png",
    name: "Alex Ramirez",
    specialization: "Orthopedics",
    experience: "15 yrs",
    qualification: "MBBS, MS (Orthopedics)",
    hospital: "CareSync Bone & Joint Center",
    address: "77, Race Course Road, Bengaluru - 560001",
    phone: "+91 95500 33445",
    email: "dr.alexramirez@caresync.in",
    availableDays: ["Tuesday", "Wednesday", "Friday"],
    consultationHours: "10:00 AM - 5:00 PM",
    consultationFee: 1100,
    rating: 4.8,
    totalPatients: 2100,
    about: "Dr. Alex Ramirez is a highly experienced orthopedic surgeon specializing in joint replacement and sports injuries. He has performed over 3000 successful surgeries and is a trusted name in musculoskeletal care.",
    languages: ["English", "Hindi", "Gujarati"],
    gender: "male",appointmentSpan: '45 mins',
  },
  {
    image: "/assets/images/dr-lee.png",
    name: "Jasmine Lee",
    specialization: "Dermatology",
    experience: "8 yrs",
    qualification: "MBBS, MD (Dermatology)",
    hospital: "CareSync Skin & Hair Clinic",
    address: "33, Anna Salai, Chennai - 600002",
    phone: "+91 94600 55667",
    email: "dr.jasminelee@caresync.in",
    availableDays: ["Monday", "Thursday", "Saturday"],
    consultationHours: "11:00 AM - 6:00 PM",
    consultationFee: 950,
    rating: 4.7,
    totalPatients: 890,
    about: "Dr. Jasmine Lee is a dermatologist with expertise in medical and cosmetic dermatology. She specializes in acne management, skin rejuvenation, and hair loss treatment using evidence-based approaches.",
    languages: ["English", "Tamil", "Hindi"],
    gender: "female",appointmentSpan: '30 mins',
  },
  {
    image: "/assets/images/dr-cruz.png",
    name: "Alyana Cruz",
    specialization: "Gynecology & Obstetrics",
    experience: "10 yrs",
    qualification: "MBBS, MS (OB-GYN)",
    hospital: "CareSync Women's Health Center",
    address: "18, Civil Lines, Jaipur - 302006",
    phone: "+91 92800 99001",
    email: "dr.alyanacruz@caresync.in",
    availableDays: ["Monday", "Wednesday", "Thursday", "Saturday"],
    consultationHours: "9:00 AM - 5:00 PM",
    consultationFee: 1000,
    rating: 4.8,
    totalPatients: 1720,
    about: "Dr. Alyana Cruz is a dedicated gynecologist and obstetrician with 10 yrs of experience in women's health. She specializes in high-risk pregnancies, laparoscopic surgeries, and reproductive health.",
    languages: ["English", "Hindi", "Rajasthani"],
    gender: "female",
    appointmentSpan: '30 mins',
  },
  {
    image: "/assets/images/dr-sharma.png",
    name: "Hardik Sharma",
    specialization: "Psychiatry",
    experience: "6 yrs",
    qualification: "MBBS, MD (Psychiatry)",
    hospital: "CareSync Mind & Wellness Clinic",
    address: "90, Gomti Nagar, Lucknow - 226010",
    phone: "+91 91900 22334",
    email: "dr.hardiksharma@caresync.in",
    availableDays: ["Tuesday", "Thursday", "Friday"],
    consultationHours: "10:00 AM - 6:00 PM",
    consultationFee: 1100,
    rating: 4.6,
    totalPatients: 540,
    about: "Dr. Hardik Sharma is a compassionate psychiatrist focused on mental health, anxiety disorders, depression, and behavioral therapy. He creates a safe, non-judgmental space for all his patients.",
    languages: ["English", "Hindi"],
    gender: "male",
    appointmentSpan: '20 mins',}
];

export const StatusIcon = {
  scheduled: "/assets/icons/check.svg",
  pending: "/assets/icons/pending.svg",
  cancelled: "/assets/icons/cancelled.svg",
};